base_url = "https://rmehri01.github.io"
compile_sass = true
build_search_index = false
theme = "terminimal"
taxonomies = [
    {name = "tags"},
]

[markdown]
highlight_code = true

[extra]
favicon = "/onenord.svg"
favicon_mimetype = "application/svg+xml"
logo_text = "🦔"
menu_items = [
    {name = "blog", url = "$BASE_URL"},
    {name = "tags", url = "$BASE_URL/tags"},
    {name = "archive", url = "$BASE_URL/archive"},
    {name = "about me", url = "$BASE_URL/about"},
    {name = "github", url = "https://github.com/rmehri01", newtab = true},
]
copyright_html = """
<span>© 2025 Ryan Mehri</span>
<span class="copyright-theme">
  <span class="copyright-theme-sep">:: </span>
  Powered by <a href="https://www.getzola.org/">Zola</a> and
  <a href="https://github.com/pawroman/zola-theme-terminimal/">Terminimal</a>
</span>
"""
